name: Update README

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행
  schedule:
    - cron: '0 0 * * *'  # 매일 자정(UTC)에 실행

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Java 환경 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: README 업데이트 스크립트 실행
        run: |
          cd src
          javac UpdateReadme.java
          java UpdateReadme

      - name: 변경사항 커밋 및 푸시
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "auto update: README.md" || echo "No changes to commit"
          git push
